server:
  port: 9209
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

spring:
  datasource:
    name: order_db
    url: jdbc:mysql://172.18.5.110:3306/user_dbcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20

fdfs:
  soTimeout: 1501
  connectTimeout: 601 
  thumbImageSize:
    width: 150
    height: 150
  trackerList:
     - 172.18.10.73:22122
  pool:
    #从池中借出的对象的最大数目
    maxTotal: 153
    #获取连接时的最大等待毫秒数100
    maxWaitMillis: 102    
  thumbImageScale:
    thumb-scale-list:
    - _middle:1.0:0.55
    - _large:1.0:0.55
    thumb-size-list:
    - _150:150:150